{"name": "Проверка невозможности логина с неверным логином", "status": "passed", "start": 1728004403697, "stop": 1728004404360, "uuid": "09c64e35-0e84-46f8-88bc-cd6e759fdad6", "historyId": "54ad6d4c7f1a40d49c5e59f6a73bdd52", "testCaseId": "54ad6d4c7f1a40d49c5e59f6a73bdd52", "fullName": "tests.test_login_user.TestsLoginUser#test_not_login_with_invalid_email", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_user"}, {"name": "subSuite", "value": "TestsLoginUser"}, {"name": "host", "value": "DESKTOP-LJDD8TD"}, {"name": "thread", "value": "5224-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}